import { Household, Child, FollowUpVisit, ChildProgressUpdate } from './types';
import { subDays, addMonths, formatISO } from 'date-fns';

const today = new Date();

export const childProgressUpdates: ChildProgressUpdate[] = [
  { id: 'cpu1', child_id: 'c1', visit_id: 'v1', is_studying: true, studying_challenges: 'Needs help with maths, requests a tutor.' },
  { id: 'cpu2', child_id: 'c2', visit_id: 'v1', is_studying: false, not_studying_reason: 'Working', is_working: true, work_details: 'Helps at a local tea stall.' },
  { id: 'cpu3', child_id: 'c3', visit_id: 'v2', is_studying: true },
  { id: 'cpu4', child_id: 'c4', visit_id: 'v3', is_studying: false, not_studying_reason: 'Financial Problems', is_working: false },
  { id: 'cpu5', child_id: 'c5', visit_id: 'v4', is_studying: true },
  { id: 'cpu6', child_id: 'c6', visit_id: 'v4', is_studying: true, studying_challenges: 'Good progress, no major issues.' },
];

export const followUpVisits: FollowUpVisit[] = [
  { id: 'v1', householdId: 'h1', visitDate: formatISO(subDays(today, 5)), visitType: 'Annual', visitedBy: 'Priya Sharma', status: 'Completed', childProgressUpdates: [childProgressUpdates[0], childProgressUpdates[1]] },
  { id: 'v2', householdId: 'h2', visitDate: formatISO(subDays(today, 10)), visitType: 'Quarterly', visitedBy: 'Priya Sharma', status: 'Completed', childProgressUpdates: [childProgressUpdates[2]] },
  { id: 'v3', householdId: 'h3', visitDate: formatISO(subDays(today, 3)), visitType: 'Quarterly', visitedBy: 'Ravi Kumar', status: 'Overdue', childProgressUpdates: [] },
  { id: 'v4', householdId: 'h4', visitDate: formatISO(subDays(today, 20)), visitType: 'Quarterly', visitedBy: 'Priya Sharma', status: 'Completed', childProgressUpdates: [childProgressUpdates[4], childProgressUpdates[5]] },
  { id: 'v5', householdId: 'h5', visitDate: formatISO(subDays(today, 8)), visitType: 'Quarterly', visitedBy: 'Ravi Kumar', status: 'Overdue', childProgressUpdates: [] },
  { id: 'v6', householdId: 'h6', visitDate: formatISO(subDays(today, 15)), visitType: 'Quarterly', visitedBy: 'Priya Sharma', status: 'Pending', childProgressUpdates: [] },
  { id: 'v7', householdId: 'h7', visitDate: formatISO(subDays(today, 25)), visitType: 'Quarterly', visitedBy: 'Priya Sharma', status: 'Pending', childProgressUpdates: [] },
];

export const children: Child[] = [
  { id: 'c1', householdId: 'h1', name: 'Amit Gupta', age: 10, gender: 'Male', isStudying: true, currentClass: '5th', schoolName: 'Govt. Public School' },
  { id: 'c2', householdId: 'h1', name: 'Sunita Gupta', age: 14, gender: 'Female', isStudying: false, currentClass: '8th', schoolName: 'Govt. Public School' },
  { id: 'c3', householdId: 'h2', name: 'Rohan Verma', age: 8, gender: 'Male', isStudying: true, currentClass: '3rd', schoolName: 'Little Angels School' },
  { id: 'c4', householdId: 'h3', name: 'Pooja Singh', age: 12, gender: 'Female', isStudying: false, currentClass: '7th', schoolName: 'City Modern School' },
  { id: 'c5', householdId: 'h4', name: 'Aarav Patel', age: 6, gender: 'Male', isStudying: true, currentClass: '1st', schoolName: 'Bright Future Academy' },
  { id: 'c6', householdId: 'h4', name: 'Meera Patel', age: 9, gender: 'Female', isStudying: true, currentClass: '4th', schoolName: 'Bright Future Academy' },
  { id: 'c7', householdId: 'h5', name: 'Vikram Reddy', age: 15, gender: 'Male', isStudying: false, currentClass: '10th', schoolName: 'National High School' },
  { id: 'c8', householdId: 'h6', name: 'Anjali Das', age: 11, gender: 'Female', isStudying: true, currentClass: '6th', schoolName: 'Sunrise School' },
  { id: 'c9', householdId: 'h7', name: 'Sanjay Kumar', age: 13, gender: 'Male', isStudying: true, currentClass: '8th', schoolName: 'Wazirpur Public School' },
];

export const households: Household[] = [
  {
    id: 'h1',
    familyName: 'Gupta Family',
    fullAddress: '123, Azadpur, Delhi',
    locationArea: 'Wazirpur',
    primaryContact: 'Rajesh Gupta',
    status: 'Active',
    nextFollowupDue: formatISO(addMonths(new Date(followUpVisits[0].visitDate), 3)),
    latitude: 28.7041,
    longitude: 77.1025,
    familyPhotoUrl: 'https://picsum.photos/seed/h1f/600/400',
    housePhotoUrl: 'https://picsum.photos/seed/h1h/600/400',
    toiletAvailable: true,
    waterSupply: 'Piped',
    electricity: true,
    annualIncome: 120000,
    children: [children[0], children[1]],
    visits: [followUpVisits[0]],
  },
  {
    id: 'h2',
    familyName: 'Verma Family',
    fullAddress: '456, Rohini Sector 5, Delhi',
    locationArea: 'Rohini',
    primaryContact: 'Suman Verma',
    status: 'Active',
    nextFollowupDue: formatISO(addMonths(new Date(followUpVisits[1].visitDate), 3)),
    latitude: 28.6863,
    longitude: 77.1496,
    familyPhotoUrl: 'https://picsum.photos/seed/h2f/600/400',
    housePhotoUrl: 'https://picsum.photos/seed/h2h/600/400',
    toiletAvailable: false,
    waterSupply: 'Tanker',
    electricity: true,
    annualIncome: 80000,
    children: [children[2]],
    visits: [followUpVisits[1]],
  },
  {
    id: 'h3',
    familyName: 'Singh Family',
    fullAddress: '789, Wazirpur JJ Colony, Delhi',
    locationArea: 'Wazirpur',
    primaryContact: 'Amit Singh',
    status: 'Active',
    nextFollowupDue: formatISO(subDays(today, 3)), // Overdue
    latitude: 28.706,
    longitude: 77.105,
    familyPhotoUrl: 'https://picsum.photos/seed/h3f/600/400',
    housePhotoUrl: 'https://picsum.photos/seed/h3h/600/400',
    toiletAvailable: false,
    waterSupply: 'Well',
    electricity: false,
    annualIncome: 60000,
    children: [children[3]],
    visits: [followUpVisits[2]],
  },
  {
    id: 'h4',
    familyName: 'Patel Family',
    fullAddress: 'A-11, Pitampura, Delhi',
    locationArea: 'Pitampura',
    primaryContact: 'Mina Patel',
    status: 'Active',
    nextFollowupDue: formatISO(addMonths(new Date(followUpVisits[3].visitDate), 3)),
    latitude: 28.6983,
    longitude: 77.1338,
    familyPhotoUrl: 'https://picsum.photos/seed/h4f/600/400',
    housePhotoUrl: 'https://picsum.photos/seed/h4h/600/400',
    toiletAvailable: true,
    waterSupply: 'Piped',
    electricity: true,
    annualIncome: 150000,
    children: [children[4], children[5]],
    visits: [followUpVisits[3]],
  },
  {
    id: 'h5',
    familyName: 'Reddy Family',
    fullAddress: 'B-4, Wazirpur Industrial Area',
    locationArea: 'Wazirpur',
    primaryContact: 'Kiran Reddy',
    status: 'Migrated',
    nextFollowupDue: formatISO(subDays(today, 8)), // Overdue
    latitude: 28.7005,
    longitude: 77.0945,
    familyPhotoUrl: 'https://picsum.photos/seed/h5f/600/400',
    housePhotoUrl: 'https://picsum.photos/seed/h5h/600/400',
    toiletAvailable: true,
    waterSupply: 'Tanker',
    electricity: true,
    annualIncome: 95000,
    children: [children[6]],
    visits: [followUpVisits[4]],
  },
  {
    id: 'h6',
    familyName: 'Das Family',
    fullAddress: 'C-Block, Shalimar Bagh',
    locationArea: 'Shalimar Bagh',
    primaryContact: 'Arun Das',
    status: 'Active',
    nextFollowupDue: formatISO(addMonths(today, 1)), // Upcoming
    latitude: 28.7178,
    longitude: 77.1537,
    familyPhotoUrl: 'https://picsum.photos/seed/h6f/600/400',
    housePhotoUrl: 'https://picsum.photos/seed/h6h/600/400',
    toiletAvailable: true,
    waterSupply: 'Piped',
    electricity: true,
    annualIncome: 200000,
    children: [children[7]],
    visits: [followUpVisits[5]],
  },
  {
    id: 'h7',
    familyName: 'Kumar Family',
    fullAddress: 'D-110, Wazirpur',
    locationArea: 'Wazirpur',
    primaryContact: 'Sunita Kumar',
    status: 'Active',
    nextFollowupDue: formatISO(addMonths(today, 0)), // Upcoming this month
    latitude: 28.7021,
    longitude: 77.1005,
    familyPhotoUrl: 'https://picsum.photos/seed/h7f/600/400',
    housePhotoUrl: 'https://picsum.photos/seed/h7h/600/400',
    toiletAvailable: false,
    waterSupply: 'Other',
    electricity: false,
    annualIncome: 75000,
    children: [children[8]],
    visits: [followUpVisits[6]],
  },
];
